routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('site.index');
});
Route::get('/',['as' => 'index', 'uses' => 'SiteController@index']);

Route::group(['as' => 'site.'], function(){
    Route::get('index',['as' => 'index', 'uses' => 'SiteController@index']);
    Route::get('quem_somos',['as' => 'quem_somos', 'uses' => 'SiteController@quem_somos']);
    Route::get('cesar',['as' => 'cesar', 'uses' => 'SiteController@cesar']);
    Route::get('curriculo',['as' => 'curriculo', 'uses' => 'SiteController@curriculo']);
    Route::get('informacoes',['as' => 'informacoes', 'uses' => 'SiteController@informacoes']);
    Route::get('fotos',['as' => 'fotos', 'uses' => 'SiteController@fotos']);
    Route::get('fotos_visualizar/{id}',['as' => 'fotos_visualizar', 'uses' => 'SiteController@fotos_visualizar']);
    Route::get('videos',['as' => 'videos', 'uses' => 'SiteController@videos']);
    Route::get('noticias',['as' => 'noticias', 'uses' => 'SiteController@noticias']);
    Route::get('noticia/{slug}',['as' => 'noticia', 'uses' => 'SiteController@noticia']);
    Route::get('cultura_surdos',['as' => 'cultura_surdos', 'uses' => 'SiteController@cultura_surdos']);
    Route::get('sobre',['as' => 'sobre', 'uses' => 'SiteController@sobre']);
    Route::get('servicos',['as' => 'servicos', 'uses' => 'SiteController@servicos']);
    Route::get('contato',['as' => 'contato', 'uses' => 'SiteController@contato']);
    Route::post('contato_enviar',['as' => 'contato_enviar', 'uses' => 'SiteController@contato_enviar']);
    Route::get('cursos',['as' => 'cursos', 'uses' => 'SiteController@cursos']);
    Route::get('curso/{id}',['as' => 'curso', 'uses' => 'SiteController@curso']);

    Route::get('carrinho',['as' => 'carrinho', 'uses' => 'SiteController@carrinho']);
    Route::post('pagseguro',['as' => 'pagseguro', 'uses' => 'PagseguroController@index']);
    Route::post('pagseguro_adicionar',['as' => 'pagseguro_adicionar', 'uses' => 'PagseguroController@adicionar']);
    Route::post('pagseguro_remover',['as' => 'pagseguro_remover', 'uses' => 'PagseguroController@remover']);

    Route::get('login',['as' => 'login', 'uses' => 'SiteController@login']);
    Route::get('logout',['as' => 'logout', 'uses' => 'SiteController@logout']);
});

/*Admin*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['web','auth','auth.checkrole:admin']], function(){
    Route::get('/',['as' => 'index', 'uses' => 'AdminHomeController@index']);
    Route::get('home',['as' => 'home', 'uses' => 'AdminHomeController@index']);

    Route::get('banners',['as' => 'banners.index', 'uses' => 'AdminBannersController@index']);
    Route::get('banners/novo',['as' => 'banners.novo', 'uses' => 'AdminBannersController@novo']);
    Route::get('banners/editar/{id}',['as' => 'banners.editar', 'uses' => 'AdminBannersController@editar']);
    Route::post('banners/salvar',['as' => 'banners.salvar', 'uses' => 'AdminBannersController@salvar']);
    Route::post('banners/atualizar/{id}',['as' => 'banners.atualizar', 'uses' => 'AdminBannersController@atualizar']);

    Route::get('fotos_categorias',['as' => 'fotos_categorias.index', 'uses' => 'AdminFotosCategoriasController@index']);
    Route::get('fotos_categorias/novo',['as' => 'fotos_categorias.novo', 'uses' => 'AdminFotosCategoriasController@novo']);
    Route::get('fotos_categorias/editar/{id}',['as' => 'fotos_categorias.editar', 'uses' => 'AdminFotosCategoriasController@editar']);
    Route::post('fotos_categorias/salvar',['as' => 'fotos_categorias.salvar', 'uses' => 'AdminFotosCategoriasController@salvar']);
    Route::post('fotos_categorias/atualizar/{id}',['as' => 'fotos_categorias.atualizar', 'uses' => 'AdminFotosCategoriasController@atualizar']);
    Route::get('fotos_categorias/delete/{id}',['as' => 'fotos_categorias.delete', 'uses' => 'AdminFotosCategoriasController@delete']);

    Route::get('fotos/{foto_categoria_id}',['as' => 'fotos.index', 'uses' => 'AdminFotosController@index']);
    Route::get('fotos/novo/{foto_categoria_id}',['as' => 'fotos.novo', 'uses' => 'AdminFotosController@novo']);
    Route::get('fotos/novo2/{foto_categoria_id}',['as' => 'fotos.novo2', 'uses' => 'AdminFotosController@novo2']);
    Route::get('fotos/editar/{id}',['as' => 'fotos.editar', 'uses' => 'AdminFotosController@editar']);
    Route::post('fotos/salvar/{foto_categoria_id}',['as' => 'fotos.salvar', 'uses' => 'AdminFotosController@salvar']);
    Route::post('fotos/salvar2/{foto_categoria_id}',['as' => 'fotos.salvar2', 'uses' => 'AdminFotosController@salvar2']);
    Route::post('fotos/atualizar/{id}',['as' => 'fotos.atualizar', 'uses' => 'AdminFotosController@atualizar']);
    Route::get('fotos/delete/{id}',['as' => 'fotos.delete', 'uses' => 'AdminFotosController@delete']);

    Route::get('noticias',['as' => 'noticias.index', 'uses' => 'AdminNoticiasController@index']);
    Route::get('noticias/novo',['as' => 'noticias.novo', 'uses' => 'AdminNoticiasController@novo']);
    Route::get('noticias/editar/{id}',['as' => 'noticias.editar', 'uses' => 'AdminNoticiasController@editar']);
    Route::post('noticias/salvar',['as' => 'noticias.salvar', 'uses' => 'AdminNoticiasController@salvar']);
    Route::post('noticias/atualizar/{id}',['as' => 'noticias.atualizar', 'uses' => 'AdminNoticiasController@atualizar']);
    Route::get('noticias/delete/{id}',['as' => 'noticias.delete', 'uses' => 'AdminNoticiasController@delete']);

    Route::get('paginas',['as' => 'paginas.index', 'uses' => 'AdminPaginasController@index']);
    Route::get('paginas/novo',['as' => 'paginas.novo', 'uses' => 'AdminPaginasController@novo']);
    Route::get('paginas/editar/{id}',['as' => 'paginas.editar', 'uses' => 'AdminPaginasController@editar']);
    Route::post('paginas/salvar',['as' => 'paginas.salvar', 'uses' => 'AdminPaginasController@salvar']);
    Route::post('paginas/atualizar/{id}',['as' => 'paginas.atualizar', 'uses' => 'AdminPaginasController@atualizar']);
    Route::get('paginas/delete/{id}',['as' => 'paginas.delete', 'uses' => 'AdminPaginasController@delete']);

    Route::get('paginas_textos/{pagina_id}',['as' => 'paginas_textos.index', 'uses' => 'AdminPaginasTextosController@index']);
    Route::get('paginas_textos/novo/{pagina_id}',['as' => 'paginas_textos.novo', 'uses' => 'AdminPaginasTextosController@novo']);
    Route::get('paginas_textos/editar/{id}',['as' => 'paginas_textos.editar', 'uses' => 'AdminPaginasTextosController@editar']);
    Route::post('paginas_textos/salvar/{pagina_id}',['as' => 'paginas_textos.salvar', 'uses' => 'AdminPaginasTextosController@salvar']);
    Route::post('paginas_textos/atualizar/{id}',['as' => 'paginas_textos.atualizar', 'uses' => 'AdminPaginasTextosController@atualizar']);
    Route::get('paginas_textos/delete/{id}',['as' => 'paginas_textos.delete', 'uses' => 'AdminPaginasTextosController@delete']);

    Route::get('colaboradores',['as' => 'colaboradores.index', 'uses' => 'AdminColaboradoresController@index']);
    Route::get('colaboradores/novo',['as' => 'colaboradores.novo', 'uses' => 'AdminColaboradoresController@novo']);
    Route::get('colaboradores/editar/{id}',['as' => 'colaboradores.editar', 'uses' => 'AdminColaboradoresController@editar']);
    Route::post('colaboradores/salvar',['as' => 'colaboradores.salvar', 'uses' => 'AdminColaboradoresController@salvar']);
    Route::post('colaboradores/atualizar/{id}',['as' => 'colaboradores.atualizar', 'uses' => 'AdminColaboradoresController@atualizar']);
    Route::get('colaboradores/delete/{id}',['as' => 'colaboradores.delete', 'uses' => 'AdminColaboradoresController@delete']);

    Route::get('depoimentos',['as' => 'depoimentos.index', 'uses' => 'AdminDepoimentosController@index']);
    Route::get('depoimentos/novo',['as' => 'depoimentos.novo', 'uses' => 'AdminDepoimentosController@novo']);
    Route::get('depoimentos/editar/{id}',['as' => 'depoimentos.editar', 'uses' => 'AdminDepoimentosController@editar']);
    Route::post('depoimentos/salvar',['as' => 'depoimentos.salvar', 'uses' => 'AdminDepoimentosController@salvar']);
    Route::post('depoimentos/atualizar/{id}',['as' => 'depoimentos.atualizar', 'uses' => 'AdminDepoimentosController@atualizar']);
    Route::get('depoimentos/delete/{id}',['as' => 'depoimentos.delete', 'uses' => 'AdminDepoimentosController@delete']);

    Route::get('users',['as' => 'users.index', 'uses' => 'AdminUsersController@index']);
    Route::get('users/novo',['as' => 'users.novo', 'uses' => 'AdminUsersController@novo']);
    Route::get('users/editar/{id}',['as' => 'users.editar', 'uses' => 'AdminUsersController@editar']);
    Route::post('users/salvar',['as' => 'users.salvar', 'uses' => 'AdminUsersController@salvar']);
    Route::post('users/atualizar/{id}',['as' => 'users.atualizar', 'uses' => 'AdminUsersController@atualizar']);
    Route::get('users/senha_editar/{id}',['as' => 'users.senha_editar', 'uses' => 'AdminUsersController@senha_editar']);
    Route::post('users/senha_atualizar/{id}',['as' => 'users.senha_atualizar', 'uses' => 'AdminUsersController@senha_atualizar']);
    Route::get('users/delete/{id}',['as' => 'users.delete', 'uses' => 'AdminUsersController@delete']);

    Route::get('cursos',['as' => 'cursos.index', 'uses' => 'AdminCursosController@index']);
    Route::get('cursos/novo',['as' => 'cursos.novo', 'uses' => 'AdminCursosController@novo']);
    Route::get('cursos/editar/{id}',['as' => 'cursos.editar', 'uses' => 'AdminCursosController@editar']);
    Route::post('cursos/salvar',['as' => 'cursos.salvar', 'uses' => 'AdminCursosController@salvar']);

resources/views/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="robots" content="noindex,nofollow">
    <title>Caesarlibras Painel</title>

    <!--CSS-->
    <link rel="stylesheet" href="{{URL::asset('css/admin_bootstrap.css')}}" >
    <link rel="stylesheet" href="{{URL::asset('fonts/font-awesome-4.6.3/css/font-awesome.min.css')}}">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{URL::asset('css/ie10-viewport-bug-workaround.css')}}" rel="stylesheet">

    <script src="{{URL::asset('js/ie-emulation-modes-warning.js')}}"></script>
    <!--[if lt IE 9]><script src="{{URL::asset('js/ie8-responsive-file-warning.js')}}"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{{URL::asset('js/html5shiv.js')}}"></script>
    <script src="{{URL::asset('js/respond.min.js')}}"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
                <img src="{{URL::asset('images/logo.png')}}" alt="" height="50">
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
                @if(!empty(Auth::user()) && Auth::user()->role == 'admin')
                    <li><a href="{{ route('admin.home') }}">Home</a></li>
                    <li><a href="{{ route('admin.paginas.index') }}">Páginas e Textos</a></li>
                    <li><a href="{{ route('admin.banners.index') }}">Banners</a></li>
                    <li><a href="{{ route('admin.fotos_categorias.index') }}">Fotos</a></li>
                    <li><a href="{{ route('admin.fotos.index',['foto_categoria_id' => 1]) }}">Vídeos</a></li>
                    <li><a href="{{ route('admin.fotos.index',['foto_categoria_id' => 7]) }}">Clientes</a></li>
                    <li><a href="{{ route('admin.noticias.index') }}">Notícias</a></li>
                    <li><a href="{{ route('admin.colaboradores.index') }}">Colaboradores</a></li>
                    {{--<li><a href="{{ route('admin.cursos.index') }}">Cursos</a></li>--}}
                    <li><a href="{{ route('admin.users.index') }}">Usuários</a></li>
                @endif
            </ul>

            <ul class="nav navbar-nav navbar-right">
                @if(auth()->guest())
                    @if(!Request::is('auth/login'))
                        <li><a href="{{ url('/auth/login') }}">Entrar</a></li>
                    @endif
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">{{ auth()->user()->name }} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ route('admin.users.editar',['id' => Auth::user()->id]) }}">
                                    <i class="fa fa-user" aria-hidden="true"></i> Perfil
                                </a>
                            </li>
                            <li><a href="{{ url('/auth/logout') }}"><i class="fa fa-sign-out" aria-hidden="true"></i> Sair</a></li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

@yield('content')

<!--JS-->
<script src="{{URL::asset('js/jquery.min.js')}}"></script>
<script src="{{URL::asset('js/jquery-migrate-1.2.1.min.js')}}"></script>
<script src="{{URL::asset('js/admin_bootstrap.min.js')}}"></script>
@yield('scripts')
</body>
</html>

resources/views/aluno.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="robots" content="noindex,nofollow">
    <title>Caesarlibras Painel</title>

    <!--CSS-->
    <link rel="stylesheet" href="{{URL::asset('css/admin_bootstrap.css')}}" >
    <link rel="stylesheet" href="{{URL::asset('fonts/font-awesome-4.6.3/css/font-awesome.min.css')}}">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{URL::asset('css/ie10-viewport-bug-workaround.css')}}" rel="stylesheet">

    <script src="{{URL::asset('js/ie-emulation-modes-warning.js')}}"></script>
    <!--[if lt IE 9]><script src="{{URL::asset('js/ie8-responsive-file-warning.js')}}"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{{URL::asset('js/html5shiv.js')}}"></script>
    <script src="{{URL::asset('js/respond.min.js')}}"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
                <img src="{{URL::asset('images/logo_area_aluno.png')}}" alt="" height="50">
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
                @if(!empty(Auth::user()) && Auth::user()->role == 'aluno')
                    <li><a href="{{ route('aluno.home') }}">Home</a></li>
                    <li><a href="{{ route('aluno.cursos') }}">Cursos</a></li>
                    <li><a href="{{ route('aluno.pedidos.index') }}">Pedidos</a></li>
                    <li><a href="{{ route('aluno.perfil.editar',['id' => Auth::user()->id]) }}">Perfil</a></li>
                @endif
            </ul>

            <ul class="nav navbar-nav navbar-right">
                @if(auth()->guest())
                    @if(!Request::is('auth/login'))
                        <li><a href="{{ url('/auth/login') }}">Entrar</a></li>
                    @endif
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">{{ auth()->user()->name }} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ route('aluno.perfil.editar',['id' => Auth::user()->id]) }}">
                                    <i class="fa fa-user" aria-hidden="true"></i> Perfil
                                </a>
                            </li>
                            <li><a href="{{ url('/auth/logout') }}"><i class="fa fa-sign-out" aria-hidden="true"></i> Sair</a></li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

@yield('content')

<!--JS-->
<script src="{{URL::asset('js/jquery.min.js')}}"></script>
<script src="{{URL::asset('js/jquery-migrate-1.2.1.min.js')}}"></script>
<script src="{{URL::asset('js/admin_bootstrap.min.js')}}"></script>
@yield('scripts')
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"></div>

                <div class="panel-body">

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/menu.blade.php
<header class="header">
    <div class="container">
        <div class="hovermenu ttmenu">
            <div class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="fa fa-bars"></span>
                    </button>
                    <div class="logo">
                        <a class="navbar-brand" href="{{route('index')}}"><img src="{{URL::asset('images/logo.png')}}" alt="Caesarlibras"></a>
                    </div>
                </div><!-- end navbar-header -->

                <div class="menu navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{{route('index')}}">Home</a>
                        </li>
                        <li class="dropdown ttmenu-half">
                            <a href="{{route('site.quem_somos')}}" class="dropdown-toggle">Quem Somos<b class="fa fa-angle-down"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{route('site.quem_somos')}}">A Empresa</a></li>
                                <li><a href="{{route('site.cesar')}}">Cesar Cunha</a></li>
                                <li><a href="{{route('site.curriculo')}}">Curriculum Vitae</a></li>
                            </ul>
                        </li>

                        <li class="dropdown ttmenu-half">
                            <a href="{{route('site.informacoes')}}" class="dropdown-toggle">Informações Gerais<b class="fa fa-angle-down"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{route('site.fotos')}}">Galeria de Fotos</a></li>
                                <li><a href="{{route('site.videos')}}">Vídeos</a></li>
                                <li><a href="{{route('site.noticias')}}">Notícias</a></li>
                                <li><a href="{{route('site.cultura_surdos')}}">Cultura dos Surdos</a></li>
                            </ul>
                        </li>
                        <li class="dropdown ttmenu-half">
                            <a href="{{route('site.sobre')}}" class="dropdown-toggle">Sobre<b class="fa fa-angle-down"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{route('site.sobre')}}#codigo_etica">Código de Ética</a></li>
                                <li><a href="{{route('site.sobre')}}#postura_profissional">Postura Profissional</a></li>
                            </ul>
                        </li>
                        <li class="dropdown ttmenu-half">
                            <a href="{{route('site.servicos')}}" class="dropdown-toggle">Serviços<b class="fa fa-angle-down"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{route('site.servicos')}}#contratacao">Contratação</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="{{route('site.contato')}}">Contato</a>
                        </li>
                    </ul><!-- end nav navbar-nav -->

                    <!--<ul class="nav navbar-nav navbar-right">
                        <li><a class="btn btn-primary" href="course-login.html"><i class="fa fa-sign-in"></i> Cadastrar</a></li>
                    </ul>-->

                </div><!--/.nav-collapse -->
            </div><!-- end navbar navbar-default clearfix -->
        </div><!-- end menu 1 -->
    </div><!-- end container -->
</header><!-- end header -->