routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('site.index');
});
Route::get('/',['as' => 'index', 'uses' => 'SiteController@index']);

Route::group(['as' => 'site.'], function(){
    Route::get('index',['as' => 'index', 'uses' => 'SiteController@index']);
    Route::get('quem_somos',['as' => 'quem_somos', 'uses' => 'SiteController@quem_somos']);
    Route::get('cesar',['as' => 'cesar', 'uses' => 'SiteController@cesar']);
    Route::get('curriculo',['as' => 'curriculo', 'uses' => 'SiteController@curriculo']);
    Route::get('informacoes',['as' => 'informacoes', 'uses' => 'SiteController@informacoes']);
    Route::get('fotos',['as' => 'fotos', 'uses' => 'SiteController@fotos']);
    Route::get('fotos_visualizar/{id}',['as' => 'fotos_visualizar', 'uses' => 'SiteController@fotos_visualizar']);
    Route::get('videos',['as' => 'videos', 'uses' => 'SiteController@videos']);
    Route::get('noticias',['as' => 'noticias', 'uses' => 'SiteController@noticias']);
    Route::get('noticia/{slug}',['as' => 'noticia', 'uses' => 'SiteController@noticia']);
    Route::get('cultura_surdos',['as' => 'cultura_surdos', 'uses' => 'SiteController@cultura_surdos']);
    Route::get('sobre',['as' => 'sobre', 'uses' => 'SiteController@sobre']);
    Route::get('servicos',['as' => 'servicos', 'uses' => 'SiteController@servicos']);
    Route::get('contato',['as' => 'contato', 'uses' => 'SiteController@contato']);
    Route::post('contato_enviar',['as' => 'contato_enviar', 'uses' => 'SiteController@contato_enviar']);
    Route::get('cursos',['as' => 'cursos', 'uses' => 'SiteController@cursos']);
    Route::get('curso/{id}',['as' => 'curso', 'uses' => 'SiteController@curso']);

    Route::get('carrinho',['as' => 'carrinho', 'uses' => 'SiteController@carrinho']);
    Route::post('pagseguro',['as' => 'pagseguro', 'uses' => 'PagseguroController@index']);
    Route::post('pagseguro_adicionar',['as' => 'pagseguro_adicionar', 'uses' => 'PagseguroController@adicionar']);
    Route::post('pagseguro_remover',['as' => 'pagseguro_remover', 'uses' => 'PagseguroController@remover']);

    Route::get('login',['as' => 'login', 'uses' => 'SiteController@login']);
    Route::get('logout',['as' => 'logout', 'uses' => 'SiteController@logout']);
});

/*Admin*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['web','auth','auth.checkrole:admin']], function(){
    Route::get('/',['as' => 'index', 'uses' => 'AdminHomeController@index']);
    Route::get('home',['as' => 'home', 'uses' => 'AdminHomeController@index']);

    Route::get('banners',['as' => 'banners.index', 'uses' => 'AdminBannersController@index']);
    Route::get('banners/novo',['as' => 'banners.novo', 'uses' => 'AdminBannersController@novo']);
    Route::get('banners/editar/{id}',['as' => 'banners.editar', 'uses' => 'AdminBannersController@editar']);
    Route::post('banners/salvar',['as' => 'banners.salvar', 'uses' => 'AdminBannersController@salvar']);
    Route::post('banners/atualizar/{id}',['as' => 'banners.atualizar', 'uses' => 'AdminBannersController@atualizar']);

    Route::get('fotos_categorias',['as' => 'fotos_categorias.index', 'uses' => 'AdminFotosCategoriasController@index']);
    Route::get('fotos_categorias/novo',['as' => 'fotos_categorias.novo', 'uses' => 'AdminFotosCategoriasController@novo']);
    Route::get('fotos_categorias/editar/{id}',['as' => 'fotos_categorias.editar', 'uses' => 'AdminFotosCategoriasController@editar']);
    Route::post('fotos_categorias/salvar',['as' => 'fotos_categorias.salvar', 'uses' => 'AdminFotosCategoriasController@salvar']);
    Route::post('fotos_categorias/atualizar/{id}',['as' => 'fotos_categorias.atualizar', 'uses' => 'AdminFotosCategoriasController@atualizar']);
    Route::get('fotos_categorias/delete/{id}',['as' => 'fotos_categorias.delete', 'uses' => 'AdminFotosCategoriasController@delete']);

    Route::get('fotos/{foto_categoria_id}',['as' => 'fotos.index', 'uses' => 'AdminFotosController@index']);
    Route::get('fotos/novo/{foto_categoria_id}',['as' => 'fotos.novo', 'uses' => 'AdminFotosController@novo']);
    Route::get('fotos/novo2/{foto_categoria_id}',['as' => 'fotos.novo2', 'uses' => 'AdminFotosController@novo2']);
    Route::get('fotos/editar/{id}',['as' => 'fotos.editar', 'uses' => 'AdminFotosController@editar']);
    Route::post('fotos/salvar/{foto_categoria_id}',['as' => 'fotos.salvar', 'uses' => 'AdminFotosController@salvar']);
    Route::post('fotos/salvar2/{foto_categoria_id}',['as' => 'fotos.salvar2', 'uses' => 'AdminFotosController@salvar2']);
    Route::post('fotos/atualizar/{id}',['as' => 'fotos.atualizar', 'uses' => 'AdminFotosController@atualizar']);
    Route::get('fotos/delete/{id}',['as' => 'fotos.delete', 'uses' => 'AdminFotosController@delete']);

    Route::get('noticias',['as' => 'noticias.index', 'uses' => 'AdminNoticiasController@index']);
    Route::get('noticias/novo',['as' => 'noticias.novo', 'uses' => 'AdminNoticiasController@novo']);
    Route::get('noticias/editar/{id}',['as' => 'noticias.editar', 'uses' => 'AdminNoticiasController@editar']);
    Route::post('noticias/salvar',['as' => 'noticias.salvar', 'uses' => 'AdminNoticiasController@salvar']);
    Route::post('noticias/atualizar/{id}',['as' => 'noticias.atualizar', 'uses' => 'AdminNoticiasController@atualizar']);
    Route::get('noticias/delete/{id}',['as' => 'noticias.delete', 'uses' => 'AdminNoticiasController@delete']);

    Route::get('paginas',['as' => 'paginas.index', 'uses' => 'AdminPaginasController@index']);
    Route::get('paginas/novo',['as' => 'paginas.novo', 'uses' => 'AdminPaginasController@novo']);
    Route::get('paginas/editar/{id}',['as' => 'paginas.editar', 'uses' => 'AdminPaginasController@editar']);
    Route::post('paginas/salvar',['as' => 'paginas.salvar', 'uses' => 'AdminPaginasController@salvar']);
    Route::post('paginas/atualizar/{id}',['as' => 'paginas.atualizar', 'uses' => 'AdminPaginasController@atualizar']);
    Route::get('paginas/delete/{id}',['as' => 'paginas.delete', 'uses' => 'AdminPaginasController@delete']);

    Route::get('paginas_textos/{pagina_id}',['as' => 'paginas_textos.index', 'uses' => 'AdminPaginasTextosController@index']);
    Route::get('paginas_textos/novo/{pagina_id}',['as' => 'paginas_textos.novo', 'uses' => 'AdminPaginasTextosController@novo']);
    Route::get('paginas_textos/editar/{id}',['as' => 'paginas_textos.editar', 'uses' => 'AdminPaginasTextosController@editar']);
    Route::post('paginas_textos/salvar/{pagina_id}',['as' => 'paginas_textos.salvar', 'uses' => 'AdminPaginasTextosController@salvar']);
    Route::post('paginas_textos/atualizar/{id}',['as' => 'paginas_textos.atualizar', 'uses' => 'AdminPaginasTextosController@atualizar']);
    Route::get('paginas_textos/delete/{id}',['as' => 'paginas_textos.delete', 'uses' => 'AdminPaginasTextosController@delete']);

    Route::get('colaboradores',['as' => 'colaboradores.index', 'uses' => 'AdminColaboradoresController@index']);
    Route::get('colaboradores/novo',['as' => 'colaboradores.novo', 'uses' => 'AdminColaboradoresController@novo']);
    Route::get('colaboradores/editar/{id}',['as' => 'colaboradores.editar', 'uses' => 'AdminColaboradoresController@editar']);
    Route::post('colaboradores/salvar',['as' => 'colaboradores.salvar', 'uses' => 'AdminColaboradoresController@salvar']);
    Route::post('colaboradores/atualizar/{id}',['as' => 'colaboradores.atualizar', 'uses' => 'AdminColaboradoresController@atualizar']);
    Route::get('colaboradores/delete/{id}',['as' => 'colaboradores.delete', 'uses' => 'AdminColaboradoresController@delete']);

    Route::get('depoimentos',['as' => 'depoimentos.index', 'uses' => 'AdminDepoimentosController@index']);
    Route::get('depoimentos/novo',['as' => 'depoimentos.novo', 'uses' => 'AdminDepoimentosController@novo']);
    Route::get('depoimentos/editar/{id}',['as' => 'depoimentos.editar', 'uses' => 'AdminDepoimentosController@editar']);
    Route::post('depoimentos/salvar',['as' => 'depoimentos.salvar', 'uses' => 'AdminDepoimentosController@salvar']);
    Route::post('depoimentos/atualizar/{id}',['as' => 'depoimentos.atualizar', 'uses' => 'AdminDepoimentosController@atualizar']);
    Route::get('depoimentos/delete/{id}',['as' => 'depoimentos.delete', 'uses' => 'AdminDepoimentosController@delete']);

    Route::get('users',['as' => 'users.index', 'uses' => 'AdminUsersController@index']);
    Route::get('users/novo',['as' => 'users.novo', 'uses' => 'AdminUsersController@novo']);
    Route::get('users/editar/{id}',['as' => 'users.editar', 'uses' => 'AdminUsersController@editar']);
    Route::post('users/salvar',['as' => 'users.salvar', 'uses' => 'AdminUsersController@salvar']);
    Route::post('users/atualizar/{id}',['as' => 'users.atualizar', 'uses' => 'AdminUsersController@atualizar']);
    Route::get('users/senha_editar/{id}',['as' => 'users.senha_editar', 'uses' => 'AdminUsersController@senha_editar']);
    Route::post('users/senha_atualizar/{id}',['as' => 'users.senha_atualizar', 'uses' => 'AdminUsersController@senha_atualizar']);
    Route::get('users/delete/{id}',['as' => 'users.delete', 'uses' => 'AdminUsersController@delete']);

    Route::get('cursos',['as' => 'cursos.index', 'uses' => 'AdminCursosController@index']);
    Route::get('cursos/novo',['as' => 'cursos.novo', 'uses' => 'AdminCursosController@novo']);
    Route::get('cursos/editar/{id}',['as' => 'cursos.editar', 'uses' => 'AdminCursosController@editar']);
    Route::post('cursos/salvar',['as' => 'cursos.salvar', 'uses' => 'AdminCursosController@salvar']);

app/Foto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Foto extends Model
{
    protected $fillable = [
        'foto_categoria_id',
        'legenda',
        'arquivo',
    ];

    public function fotoCategoria()
    {
        return $this->belongsTo('App\FotoCategoria');
    }
}

resources/views/admin/fotos/editar.blade.php
@extends('admin')

@section('content')

    <div class="container">
        <h3>@if(!empty($botoes['titulo']) && strpos($botoes['titulo'],'Fotos') !== false)Fotos - @endif<strong>{{$foto_categoria->nome}}</strong></h3>

        <br>
        <a href="{{ route('admin.fotos.index',['foto_categoria_id' => $foto_categoria_id]) }}" class="btn btn-default"><i class="fa fa-arrow-circle-o-left" aria-hidden="true"></i> Voltar</a>
        <br><br>

        @include('errors.mensagens')

        {!! Form::model($foto, ['route' => ['admin.fotos.atualizar', $foto->id], 'class' => 'form']) !!}

        @include('admin.fotos.form_editar')

        {!! Form::close() !!}

    </div>

@endsection

resources/views/admin/fotos/form.blade.php
{!! Form::token() !!}
@for($i = 0; $i < 10; $i++)
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group {{$botoes['css_class']}}">
                {!! Form::label('arquivo'.$i,$botoes['titulo2'].' '.($i+1).':') !!}
                {!! Form::text('arquivo'.$i, null, ['name' => 'foto['.$i.'][arquivo]','class' => 'form-control']) !!}
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                {!! Form::label('legenda'.$i,'Legenda '.($i+1).':') !!}
                {!! Form::text('legenda'.$i, null, ['name' => 'foto['.$i.'][legenda]','class' => 'form-control']) !!}
            </div>
        </div>
    </div>
<hr>
@endfor

<div class="form-group">
    <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o" aria-hidden="true"></i> Salvar</button>
</div>

@section('scripts')
    @if($botoes['titulo'] != 'video')
        @include('includes.filemanager')
        <script>
            $(function(){
                @for($i = 0; $i < 10; $i++)
                filemanager_abrir('arquivo{{$i}}');
                @endfor
            });
        </script>
    @endif
    @include('includes.validate')
@endsection

resources/views/admin/fotos/form_editar.blade.php
{!! Form::token() !!}

<div class="row">
    <div class="col-lg-6">
        <div class="form-group {{$botoes['css_class']}}">
            {!! Form::label('arquivo',$botoes['titulo2'].':') !!}
            {!! Form::text('arquivo', null, ['name' => 'arquivo','class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-lg-6">
        <div class="form-group">
            {!! Form::label('legenda','Legenda :') !!}
            {!! Form::text('legenda', null, ['name' => 'legenda','class' => 'form-control']) !!}
        </div>
    </div>
</div>

<div class="form-group">
    <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o" aria-hidden="true"></i> Salvar</button>
</div>

@section('scripts')
    @if($botoes['titulo'] != 'video')
        @include('includes.filemanager')
        <script>
            $(function(){
                filemanager_abrir('arquivo');
            });
        </script>
    @endif
    @include('includes.validate')
@endsection

resources/views/admin/fotos/index.blade.php
@extends('admin')

@section('content')

<div class="container">
    <h3>@if(!empty($botoes['titulo']) && strpos($botoes['titulo'],'Fotos') !== false) Fotos - @endif<strong>{{$foto_categoria->nome}}</strong></h3>

    <br>
    <a href="{{ route('admin.fotos.novo2',['id' => $foto_categoria_id]) }}" class="btn btn-default"><i class="fa fa-plus-circle" aria-hidden="true"></i> {{$botoes['novo']}}</a>
    @if(!empty($botoes['voltar']))
    <a href="{{ route('admin.fotos_categorias.index') }}" class="btn btn-default"><i class="fa fa-arrow-circle-o-left" aria-hidden="true"></i> {{$botoes['voltar']}}</a>
    @endif
    <br><br>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>{{$botoes['titulo2']}}</th>
            <th>Legenda</th>
            <th width="15%">Ação</th>
        </tr>
        </thead>
        <tbody>
        @foreach($fotos as $v)
        <tr>
            <td>
                @if(strpos($v->arquivo,'youtube') !== false || strpos($v->arquivo,'youtu.be') !== false)
                    {!! Youtube::thumb($v->arquivo,'mq') !!}
                @elseif(strpos($v->arquivo,'vimeo') !== false)
                    {!! Vimeo::thumb($v->arquivo) !!}
                @else
                    {!! Thumb::img($v->arquivo) !!}
                @endif
            </td>
            <td>{{$v->legenda}}</td>
            <td>
                <a href="{{ route('admin.fotos.editar',['id' => $v->id]) }}" class="btn btn-default btn-xs"><i class="fa fa-pencil" aria-hidden="true"></i> editar</a>
                <a href="{{ route('admin.fotos.delete',['id' => $v->id]) }}" class="btn btn-danger btn-xs delete"><i class="fa fa-trash" aria-hidden="true"></i> excluir</a>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>

    {!! $fotos->render() !!}
</div>

@endsection

@section('scripts')
    @include('includes.delete_alert')
@endsection

resources/views/admin/fotos/novo.blade.php
@extends('admin')

@section('content')

    <div class="container">
        <h3>Fotos - <strong>{{$foto_categoria->nome}}</strong></h3>

        <br>
        <a href="{{ route('admin.fotos.index',['foto_categoria_id' => $foto_categoria->id]) }}" class="btn btn-default"><i class="fa fa-arrow-circle-o-left" aria-hidden="true"></i> Voltar</a>
        <br><br>

        <div id='fotosList'>
            <table class='fotosEditor table table-striped'>
                <thead>
                <tr>
                    <th width="50%">Fotos</th>
                    <th width="45%">Legenda</th>
                    <th width="5%"></th>
                </tr>
                </thead>
                <tbody data-bind="foreach: fotos">
                <tr>
                    <td>
                        <div class="form-group input-group">
                        <input class="form-control" data-bind='value: arquivo, attr:{"id":"foto"+$index()}' />
                        <span class="input-group-btn">
                            <a data-bind='click:function(){$parent.filemanager_abrir2("foto"+$index())}' class="btn btn-default filemanager-btn" target="_blank">Selecionar Imagem</a>
                        </span>
                        </div>
                    </td>
                    <td>
                        <input class="form-control" data-bind='value: legenda' />
                    </td>
                    <td>
                        <div><a href='#' data-bind='click: $root.removeFoto' class="btn btn-danger btn-xs"><i class="fa fa-trash-o" aria-hidden="true"></i> remover</a></div>
                    </td>
                </tr>
                </tbody>
            </table>
            <p>
                <button data-bind='click: save' class="btn btn-sx btn-primary">Salvar</button>
                <button data-bind='click: addFoto' class="btn btn-sx btn-warning"><i class="fa fa-plus-circle" aria-hidden="true"></i> Nova Fotos</button>
                <span class="ajax-load" style="display: none;">
                    <img src="{{URL::asset('img/ajax_load.gif')}}" alt="">
                    <strong>Salvando, aguarde!</strong>
                </span>
            </p>

            {!! Form::open(['url' => '/admin/fotos/salvar/'.$foto_categoria_id, 'method' => 'post', 'class' => 'form']) !!}
            <input type="hidden" name="fotos" id="fotos">
            {!! Form::close() !!}

        </div>
    </div>
@endsection
@section('scripts')
    @include('includes.filemanager')
    <script src="{{ URL::asset('js/knockoutjs/knockout-3.4.0.js') }}"></script>
    <script>
        $(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var initialData = [
                {id:"", foto_categoria_id:"{{$foto_categoria->id}}", legenda:"", arquivo: ""},
                {id:"", foto_categoria_id:"{{$foto_categoria->id}}", legenda:"", arquivo: ""},
                {id:"", foto_categoria_id:"{{$foto_categoria->id}}", legenda:"", arquivo: ""},
                {id:"", foto_categoria_id:"{{$foto_categoria->id}}", legenda:"", arquivo: ""},
                {id:"", foto_categoria_id:"{{$foto_categoria->id}}", legenda:"", arquivo: ""}
            ];

            var FotosModel = function(fotos) {
                var self = this;
                self.fotos = ko.observableArray(ko.utils.arrayMap(fotos, function(foto) {
                    return {
                        id: foto.id,
                        foto_categoria_id: foto.foto_categoria_id,
                        legenda: foto.legenda,
                        arquivo: foto.arquivo
                    };
                }));

                self.filemanager_abrir2 = function(id){
                    open_popup('/js/filemanager/dialog.php?type=1&popup=1&field_id='+id+'&relative_url=1&sort_by=date&descending=1');
                };

                self.foto_categoria = ko.observable({{$foto_categoria_id}});
                self.arquivo = ko.observable();
                self.legenda = ko.observable();

                self.addFoto = function() {
                    self.fotos.push({
                        id: "",
                        foto_categoria_id: self.foto_categoria(),
                        arquivo: self.arquivo(),
                        legenda: self.legenda()
                    });
                };

                self.removeFoto = function(foto) {
                    var confirma = confirm('Deseja excluir esta foto?');
                    if (confirma) {
                        self.fotos.remove(foto);
                    }
                };

                self.save = function() {
                    $('.ajax-load').show();
                    /*var valores = JSON.stringify(ko.toJS(self.fotos,null,2));
                    console.log(valores);*/
                    var valores = JSON.stringify(ko.toJS(self.fotos));
                    $('#fotos').val(valores);
                    $('form').trigger('submit');
                };

            };

            ko.applyBindings(new FotosModel(initialData));
        });
    </script>

@endsection

resources/views/admin/fotos/novo2.blade.php
@extends('admin')

@section('content')

    <div class="container">
        <h3>@if(!empty($botoes['titulo']) && strpos($botoes['titulo'],'Fotos') !== false) Fotos - @endif<strong>{{$foto_categoria->nome}}</strong></h3>

        <br>
        <a href="{{ route('admin.fotos.index',['foto_categoria_id' => $foto_categoria_id]) }}" class="btn btn-default"><i class="fa fa-arrow-circle-o-left" aria-hidden="true"></i> Voltar</a>
        <br><br>

        @include('errors.mensagens')

        {!! Form::open(['route' => ['admin.fotos.salvar2', $foto_categoria_id], 'class' => 'form']) !!}

        @include('admin.fotos.form')

        {!! Form::close() !!}

    </div>

@endsection