routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('site.index');
});
Route::get('/',['as' => 'index', 'uses' => 'SiteController@index']);

Route::group(['as' => 'site.'], function(){
    Route::get('index',['as' => 'index', 'uses' => 'SiteController@index']);
    Route::get('quem_somos',['as' => 'quem_somos', 'uses' => 'SiteController@quem_somos']);
    Route::get('cesar',['as' => 'cesar', 'uses' => 'SiteController@cesar']);
    Route::get('curriculo',['as' => 'curriculo', 'uses' => 'SiteController@curriculo']);
    Route::get('informacoes',['as' => 'informacoes', 'uses' => 'SiteController@informacoes']);
    Route::get('fotos',['as' => 'fotos', 'uses' => 'SiteController@fotos']);
    Route::get('fotos_visualizar/{id}',['as' => 'fotos_visualizar', 'uses' => 'SiteController@fotos_visualizar']);
    Route::get('videos',['as' => 'videos', 'uses' => 'SiteController@videos']);
    Route::get('noticias',['as' => 'noticias', 'uses' => 'SiteController@noticias']);
    Route::get('noticia/{slug}',['as' => 'noticia', 'uses' => 'SiteController@noticia']);
    Route::get('cultura_surdos',['as' => 'cultura_surdos', 'uses' => 'SiteController@cultura_surdos']);
    Route::get('sobre',['as' => 'sobre', 'uses' => 'SiteController@sobre']);
    Route::get('servicos',['as' => 'servicos', 'uses' => 'SiteController@servicos']);
    Route::get('contato',['as' => 'contato', 'uses' => 'SiteController@contato']);
    Route::post('contato_enviar',['as' => 'contato_enviar', 'uses' => 'SiteController@contato_enviar']);
    Route::get('cursos',['as' => 'cursos', 'uses' => 'SiteController@cursos']);
    Route::get('curso/{id}',['as' => 'curso', 'uses' => 'SiteController@curso']);

    Route::get('carrinho',['as' => 'carrinho', 'uses' => 'SiteController@carrinho']);
    Route::post('pagseguro',['as' => 'pagseguro', 'uses' => 'PagseguroController@index']);
    Route::post('pagseguro_adicionar',['as' => 'pagseguro_adicionar', 'uses' => 'PagseguroController@adicionar']);
    Route::post('pagseguro_remover',['as' => 'pagseguro_remover', 'uses' => 'PagseguroController@remover']);

    Route::get('login',['as' => 'login', 'uses' => 'SiteController@login']);
    Route::get('logout',['as' => 'logout', 'uses' => 'SiteController@logout']);
});

/*Admin*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['web','auth','auth.checkrole:admin']], function(){
    Route::get('/',['as' => 'index', 'uses' => 'AdminHomeController@index']);
    Route::get('home',['as' => 'home', 'uses' => 'AdminHomeController@index']);

    Route::get('banners',['as' => 'banners.index', 'uses' => 'AdminBannersController@index']);
    Route::get('banners/novo',['as' => 'banners.novo', 'uses' => 'AdminBannersController@novo']);
    Route::get('banners/editar/{id}',['as' => 'banners.editar', 'uses' => 'AdminBannersController@editar']);
    Route::post('banners/salvar',['as' => 'banners.salvar', 'uses' => 'AdminBannersController@salvar']);
    Route::post('banners/atualizar/{id}',['as' => 'banners.atualizar', 'uses' => 'AdminBannersController@atualizar']);

    Route::get('fotos_categorias',['as' => 'fotos_categorias.index', 'uses' => 'AdminFotosCategoriasController@index']);
    Route::get('fotos_categorias/novo',['as' => 'fotos_categorias.novo', 'uses' => 'AdminFotosCategoriasController@novo']);
    Route::get('fotos_categorias/editar/{id}',['as' => 'fotos_categorias.editar', 'uses' => 'AdminFotosCategoriasController@editar']);
    Route::post('fotos_categorias/salvar',['as' => 'fotos_categorias.salvar', 'uses' => 'AdminFotosCategoriasController@salvar']);
    Route::post('fotos_categorias/atualizar/{id}',['as' => 'fotos_categorias.atualizar', 'uses' => 'AdminFotosCategoriasController@atualizar']);
    Route::get('fotos_categorias/delete/{id}',['as' => 'fotos_categorias.delete', 'uses' => 'AdminFotosCategoriasController@delete']);

    Route::get('fotos/{foto_categoria_id}',['as' => 'fotos.index', 'uses' => 'AdminFotosController@index']);
    Route::get('fotos/novo/{foto_categoria_id}',['as' => 'fotos.novo', 'uses' => 'AdminFotosController@novo']);
    Route::get('fotos/novo2/{foto_categoria_id}',['as' => 'fotos.novo2', 'uses' => 'AdminFotosController@novo2']);
    Route::get('fotos/editar/{id}',['as' => 'fotos.editar', 'uses' => 'AdminFotosController@editar']);
    Route::post('fotos/salvar/{foto_categoria_id}',['as' => 'fotos.salvar', 'uses' => 'AdminFotosController@salvar']);
    Route::post('fotos/salvar2/{foto_categoria_id}',['as' => 'fotos.salvar2', 'uses' => 'AdminFotosController@salvar2']);
    Route::post('fotos/atualizar/{id}',['as' => 'fotos.atualizar', 'uses' => 'AdminFotosController@atualizar']);
    Route::get('fotos/delete/{id}',['as' => 'fotos.delete', 'uses' => 'AdminFotosController@delete']);

    Route::get('noticias',['as' => 'noticias.index', 'uses' => 'AdminNoticiasController@index']);
    Route::get('noticias/novo',['as' => 'noticias.novo', 'uses' => 'AdminNoticiasController@novo']);
    Route::get('noticias/editar/{id}',['as' => 'noticias.editar', 'uses' => 'AdminNoticiasController@editar']);
    Route::post('noticias/salvar',['as' => 'noticias.salvar', 'uses' => 'AdminNoticiasController@salvar']);
    Route::post('noticias/atualizar/{id}',['as' => 'noticias.atualizar', 'uses' => 'AdminNoticiasController@atualizar']);
    Route::get('noticias/delete/{id}',['as' => 'noticias.delete', 'uses' => 'AdminNoticiasController@delete']);

    Route::get('paginas',['as' => 'paginas.index', 'uses' => 'AdminPaginasController@index']);
    Route::get('paginas/novo',['as' => 'paginas.novo', 'uses' => 'AdminPaginasController@novo']);
    Route::get('paginas/editar/{id}',['as' => 'paginas.editar', 'uses' => 'AdminPaginasController@editar']);
    Route::post('paginas/salvar',['as' => 'paginas.salvar', 'uses' => 'AdminPaginasController@salvar']);
    Route::post('paginas/atualizar/{id}',['as' => 'paginas.atualizar', 'uses' => 'AdminPaginasController@atualizar']);
    Route::get('paginas/delete/{id}',['as' => 'paginas.delete', 'uses' => 'AdminPaginasController@delete']);

    Route::get('paginas_textos/{pagina_id}',['as' => 'paginas_textos.index', 'uses' => 'AdminPaginasTextosController@index']);
    Route::get('paginas_textos/novo/{pagina_id}',['as' => 'paginas_textos.novo', 'uses' => 'AdminPaginasTextosController@novo']);
    Route::get('paginas_textos/editar/{id}',['as' => 'paginas_textos.editar', 'uses' => 'AdminPaginasTextosController@editar']);
    Route::post('paginas_textos/salvar/{pagina_id}',['as' => 'paginas_textos.salvar', 'uses' => 'AdminPaginasTextosController@salvar']);
    Route::post('paginas_textos/atualizar/{id}',['as' => 'paginas_textos.atualizar', 'uses' => 'AdminPaginasTextosController@atualizar']);
    Route::get('paginas_textos/delete/{id}',['as' => 'paginas_textos.delete', 'uses' => 'AdminPaginasTextosController@delete']);

    Route::get('colaboradores',['as' => 'colaboradores.index', 'uses' => 'AdminColaboradoresController@index']);
    Route::get('colaboradores/novo',['as' => 'colaboradores.novo', 'uses' => 'AdminColaboradoresController@novo']);
    Route::get('colaboradores/editar/{id}',['as' => 'colaboradores.editar', 'uses' => 'AdminColaboradoresController@editar']);
    Route::post('colaboradores/salvar',['as' => 'colaboradores.salvar', 'uses' => 'AdminColaboradoresController@salvar']);
    Route::post('colaboradores/atualizar/{id}',['as' => 'colaboradores.atualizar', 'uses' => 'AdminColaboradoresController@atualizar']);
    Route::get('colaboradores/delete/{id}',['as' => 'colaboradores.delete', 'uses' => 'AdminColaboradoresController@delete']);

    Route::get('depoimentos',['as' => 'depoimentos.index', 'uses' => 'AdminDepoimentosController@index']);
    Route::get('depoimentos/novo',['as' => 'depoimentos.novo', 'uses' => 'AdminDepoimentosController@novo']);
    Route::get('depoimentos/editar/{id}',['as' => 'depoimentos.editar', 'uses' => 'AdminDepoimentosController@editar']);
    Route::post('depoimentos/salvar',['as' => 'depoimentos.salvar', 'uses' => 'AdminDepoimentosController@salvar']);
    Route::post('depoimentos/atualizar/{id}',['as' => 'depoimentos.atualizar', 'uses' => 'AdminDepoimentosController@atualizar']);
    Route::get('depoimentos/delete/{id}',['as' => 'depoimentos.delete', 'uses' => 'AdminDepoimentosController@delete']);

    Route::get('users',['as' => 'users.index', 'uses' => 'AdminUsersController@index']);
    Route::get('users/novo',['as' => 'users.novo', 'uses' => 'AdminUsersController@novo']);
    Route::get('users/editar/{id}',['as' => 'users.editar', 'uses' => 'AdminUsersController@editar']);
    Route::post('users/salvar',['as' => 'users.salvar', 'uses' => 'AdminUsersController@salvar']);
    Route::post('users/atualizar/{id}',['as' => 'users.atualizar', 'uses' => 'AdminUsersController@atualizar']);
    Route::get('users/senha_editar/{id}',['as' => 'users.senha_editar', 'uses' => 'AdminUsersController@senha_editar']);
    Route::post('users/senha_atualizar/{id}',['as' => 'users.senha_atualizar', 'uses' => 'AdminUsersController@senha_atualizar']);
    Route::get('users/delete/{id}',['as' => 'users.delete', 'uses' => 'AdminUsersController@delete']);

    Route::get('cursos',['as' => 'cursos.index', 'uses' => 'AdminCursosController@index']);
    Route::get('cursos/novo',['as' => 'cursos.novo', 'uses' => 'AdminCursosController@novo']);
    Route::get('cursos/editar/{id}',['as' => 'cursos.editar', 'uses' => 'AdminCursosController@editar']);
    Route::post('cursos/salvar',['as' => 'cursos.salvar', 'uses' => 'AdminCursosController@salvar']);

app/Noticia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Noticia extends Model
{
    protected $fillable = [
        'titulo',
        'slug',
        'texto',
        'arquivo',
        'publicado',
    ];
}

resources/views/admin/noticias/editar.blade.php
@extends('admin')

@section('content')

    <div class="container">
        <h3>Editar Notícia:</h3>

        <br>
        <a href="{{ route('admin.noticias.index') }}" class="btn btn-default"><i class="fa fa-arrow-circle-o-left" aria-hidden="true"></i> Voltar</a>
        <br><br>

        @include('errors.mensagens')

        {!! Form::model($noticia, ['route' => ['admin.noticias.atualizar', $noticia->id], 'class' => 'form']) !!}

        @include('admin.noticias.form')

        {!! Form::close() !!}

    </div>

@endsection

resources/views/admin/noticias/form.blade.php
{!! Form::token() !!}
<div class="form-group">
    {!! Form::label('titulo','Título:') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control required']) !!}
</div>

<div class="form-group">
    {!! Form::label('slug','URL:') !!}
    <div class="input-group">
        <span class="input-group-addon">http://caesarlibras.com.br/noticia/</span>
        {!! Form::text('slug', null, ['class' => 'form-control required']) !!}
    </div>
</div>

<div class="form-group input-group">
    {!! Form::label('arquivo','Imagem:') !!}
    {!! Form::text('arquivo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto','Texto:') !!}
    {!! Form::textarea('texto', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('publicado','Publicado:') !!}
    {!! Form::select('publicado', ['1' => 'Sim','2' => 'Não'], null, ['class' => 'form-control required']) !!}
</div>

<div class="form-group">
    <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o" aria-hidden="true"></i> Salvar</button>
</div>

@section('scripts')
    <script src="{{URL::asset('js/slugify.js')}}"></script>
    <script src="{{URL::asset('js/remove_acentos.js')}}"></script>
    @include('includes.filemanager')
    @include('includes.ckeditor',['ckeditor_id' => 'texto'])
    <script>
        $(function(){
            $('#titulo').change(function(){
                var valor = $(this).val();
                $('#slug').val(slugify(remove_acentos(valor)));
            });

            filemanager_abrir('arquivo');
        });
    </script>
    @include('includes.validate')
@endsection

resources/views/admin/noticias/index.blade.php
@extends('admin')

@section('content')

<div class="container">
    <h3>Notícias</h3>

    <br>
    <a href="{{ route('admin.noticias.novo') }}" class="btn btn-default"><i class="fa fa-plus-circle" aria-hidden="true"></i> Novo Notícia</a>
    <br><br>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Título</th>
            <th>Imagem</th>
            <th>Data</th>
            <th>Publicado</th>
            <th width="15%">Ação</th>
        </tr>
        </thead>
        <tbody>
        @foreach($noticias as $v)
        <tr>
            <td>{{$v->titulo}}</td>
            <td>
                @if(!empty($v->arquivo))
                    {!! Thumb::img($v->arquivo) !!}
                @else
                    <img src="{{URL::asset('img/img-vazio.png')}}" alt="" class="img-responsive" style="width: 200px;">
                @endif
            </td>
            <td>{{Formata::date($v->created_at)}}</td>
            <td>{{Status::label_publicado($v->publicado)}}</td>
            <td>
                <a href="{{ route('admin.noticias.editar',['id' => $v->id]) }}" class="btn btn-default btn-xs"><i class="fa fa-pencil" aria-hidden="true"></i> editar</a>
                <a href="{{ route('admin.noticias.delete',['id' => $v->id]) }}" class="btn btn-danger btn-xs delete"><i class="fa fa-trash" aria-hidden="true"></i> excluir</a>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>

    {!! $noticias->render() !!}
</div>

@endsection

@section('scripts')
    @include('includes.delete_alert')
@endsection

resources/views/admin/noticias/novo.blade.php
@extends('admin')

@section('content')

    <div class="container">
        <h3>Novo Notícia</h3>

        <br>
        <a href="{{ route('admin.noticias.index') }}" class="btn btn-default"><i class="fa fa-arrow-circle-o-left" aria-hidden="true"></i> Voltar</a>
        <br><br>

        @include('errors.mensagens')

        {!! Form::open(['route' => 'admin.noticias.salvar', 'class' => 'form']) !!}

        @include('admin.noticias.form')

        {!! Form::close() !!}

    </div>

@endsection