routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('site.index');
});
Route::get('/',['as' => 'index', 'uses' => 'SiteController@index']);

Route::group(['as' => 'site.'], function(){
    Route::get('index',['as' => 'index', 'uses' => 'SiteController@index']);
    Route::get('quem_somos',['as' => 'quem_somos', 'uses' => 'SiteController@quem_somos']);
    Route::get('cesar',['as' => 'cesar', 'uses' => 'SiteController@cesar']);
    Route::get('curriculo',['as' => 'curriculo', 'uses' => 'SiteController@curriculo']);
    Route::get('informacoes',['as' => 'informacoes', 'uses' => 'SiteController@informacoes']);
    Route::get('fotos',['as' => 'fotos', 'uses' => 'SiteController@fotos']);
    Route::get('fotos_visualizar/{id}',['as' => 'fotos_visualizar', 'uses' => 'SiteController@fotos_visualizar']);
    Route::get('videos',['as' => 'videos', 'uses' => 'SiteController@videos']);
    Route::get('noticias',['as' => 'noticias', 'uses' => 'SiteController@noticias']);
    Route::get('noticia/{slug}',['as' => 'noticia', 'uses' => 'SiteController@noticia']);
    Route::get('cultura_surdos',['as' => 'cultura_surdos', 'uses' => 'SiteController@cultura_surdos']);
    Route::get('sobre',['as' => 'sobre', 'uses' => 'SiteController@sobre']);
    Route::get('servicos',['as' => 'servicos', 'uses' => 'SiteController@servicos']);
    Route::get('contato',['as' => 'contato', 'uses' => 'SiteController@contato']);
    Route::post('contato_enviar',['as' => 'contato_enviar', 'uses' => 'SiteController@contato_enviar']);
    Route::get('cursos',['as' => 'cursos', 'uses' => 'SiteController@cursos']);
    Route::get('curso/{id}',['as' => 'curso', 'uses' => 'SiteController@curso']);

    Route::get('carrinho',['as' => 'carrinho', 'uses' => 'SiteController@carrinho']);
    Route::post('pagseguro',['as' => 'pagseguro', 'uses' => 'PagseguroController@index']);
    Route::post('pagseguro_adicionar',['as' => 'pagseguro_adicionar', 'uses' => 'PagseguroController@adicionar']);
    Route::post('pagseguro_remover',['as' => 'pagseguro_remover', 'uses' => 'PagseguroController@remover']);

    Route::get('login',['as' => 'login', 'uses' => 'SiteController@login']);
    Route::get('logout',['as' => 'logout', 'uses' => 'SiteController@logout']);
});

/*Admin*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['web','auth','auth.checkrole:admin']], function(){
    Route::get('/',['as' => 'index', 'uses' => 'AdminHomeController@index']);
    Route::get('home',['as' => 'home', 'uses' => 'AdminHomeController@index']);

    Route::get('banners',['as' => 'banners.index', 'uses' => 'AdminBannersController@index']);
    Route::get('banners/novo',['as' => 'banners.novo', 'uses' => 'AdminBannersController@novo']);
    Route::get('banners/editar/{id}',['as' => 'banners.editar', 'uses' => 'AdminBannersController@editar']);
    Route::post('banners/salvar',['as' => 'banners.salvar', 'uses' => 'AdminBannersController@salvar']);
    Route::post('banners/atualizar/{id}',['as' => 'banners.atualizar', 'uses' => 'AdminBannersController@atualizar']);

    Route::get('fotos_categorias',['as' => 'fotos_categorias.index', 'uses' => 'AdminFotosCategoriasController@index']);
    Route::get('fotos_categorias/novo',['as' => 'fotos_categorias.novo', 'uses' => 'AdminFotosCategoriasController@novo']);
    Route::get('fotos_categorias/editar/{id}',['as' => 'fotos_categorias.editar', 'uses' => 'AdminFotosCategoriasController@editar']);
    Route::post('fotos_categorias/salvar',['as' => 'fotos_categorias.salvar', 'uses' => 'AdminFotosCategoriasController@salvar']);
    Route::post('fotos_categorias/atualizar/{id}',['as' => 'fotos_categorias.atualizar', 'uses' => 'AdminFotosCategoriasController@atualizar']);
    Route::get('fotos_categorias/delete/{id}',['as' => 'fotos_categorias.delete', 'uses' => 'AdminFotosCategoriasController@delete']);

    Route::get('fotos/{foto_categoria_id}',['as' => 'fotos.index', 'uses' => 'AdminFotosController@index']);
    Route::get('fotos/novo/{foto_categoria_id}',['as' => 'fotos.novo', 'uses' => 'AdminFotosController@novo']);
    Route::get('fotos/novo2/{foto_categoria_id}',['as' => 'fotos.novo2', 'uses' => 'AdminFotosController@novo2']);
    Route::get('fotos/editar/{id}',['as' => 'fotos.editar', 'uses' => 'AdminFotosController@editar']);
    Route::post('fotos/salvar/{foto_categoria_id}',['as' => 'fotos.salvar', 'uses' => 'AdminFotosController@salvar']);
    Route::post('fotos/salvar2/{foto_categoria_id}',['as' => 'fotos.salvar2', 'uses' => 'AdminFotosController@salvar2']);
    Route::post('fotos/atualizar/{id}',['as' => 'fotos.atualizar', 'uses' => 'AdminFotosController@atualizar']);
    Route::get('fotos/delete/{id}',['as' => 'fotos.delete', 'uses' => 'AdminFotosController@delete']);

    Route::get('noticias',['as' => 'noticias.index', 'uses' => 'AdminNoticiasController@index']);
    Route::get('noticias/novo',['as' => 'noticias.novo', 'uses' => 'AdminNoticiasController@novo']);
    Route::get('noticias/editar/{id}',['as' => 'noticias.editar', 'uses' => 'AdminNoticiasController@editar']);
    Route::post('noticias/salvar',['as' => 'noticias.salvar', 'uses' => 'AdminNoticiasController@salvar']);
    Route::post('noticias/atualizar/{id}',['as' => 'noticias.atualizar', 'uses' => 'AdminNoticiasController@atualizar']);
    Route::get('noticias/delete/{id}',['as' => 'noticias.delete', 'uses' => 'AdminNoticiasController@delete']);

    Route::get('paginas',['as' => 'paginas.index', 'uses' => 'AdminPaginasController@index']);
    Route::get('paginas/novo',['as' => 'paginas.novo', 'uses' => 'AdminPaginasController@novo']);
    Route::get('paginas/editar/{id}',['as' => 'paginas.editar', 'uses' => 'AdminPaginasController@editar']);
    Route::post('paginas/salvar',['as' => 'paginas.salvar', 'uses' => 'AdminPaginasController@salvar']);
    Route::post('paginas/atualizar/{id}',['as' => 'paginas.atualizar', 'uses' => 'AdminPaginasController@atualizar']);
    Route::get('paginas/delete/{id}',['as' => 'paginas.delete', 'uses' => 'AdminPaginasController@delete']);

    Route::get('paginas_textos/{pagina_id}',['as' => 'paginas_textos.index', 'uses' => 'AdminPaginasTextosController@index']);
    Route::get('paginas_textos/novo/{pagina_id}',['as' => 'paginas_textos.novo', 'uses' => 'AdminPaginasTextosController@novo']);
    Route::get('paginas_textos/editar/{id}',['as' => 'paginas_textos.editar', 'uses' => 'AdminPaginasTextosController@editar']);
    Route::post('paginas_textos/salvar/{pagina_id}',['as' => 'paginas_textos.salvar', 'uses' => 'AdminPaginasTextosController@salvar']);
    Route::post('paginas_textos/atualizar/{id}',['as' => 'paginas_textos.atualizar', 'uses' => 'AdminPaginasTextosController@atualizar']);
    Route::get('paginas_textos/delete/{id}',['as' => 'paginas_textos.delete', 'uses' => 'AdminPaginasTextosController@delete']);

    Route::get('colaboradores',['as' => 'colaboradores.index', 'uses' => 'AdminColaboradoresController@index']);
    Route::get('colaboradores/novo',['as' => 'colaboradores.novo', 'uses' => 'AdminColaboradoresController@novo']);
    Route::get('colaboradores/editar/{id}',['as' => 'colaboradores.editar', 'uses' => 'AdminColaboradoresController@editar']);
    Route::post('colaboradores/salvar',['as' => 'colaboradores.salvar', 'uses' => 'AdminColaboradoresController@salvar']);
    Route::post('colaboradores/atualizar/{id}',['as' => 'colaboradores.atualizar', 'uses' => 'AdminColaboradoresController@atualizar']);
    Route::get('colaboradores/delete/{id}',['as' => 'colaboradores.delete', 'uses' => 'AdminColaboradoresController@delete']);

    Route::get('depoimentos',['as' => 'depoimentos.index', 'uses' => 'AdminDepoimentosController@index']);
    Route::get('depoimentos/novo',['as' => 'depoimentos.novo', 'uses' => 'AdminDepoimentosController@novo']);
    Route::get('depoimentos/editar/{id}',['as' => 'depoimentos.editar', 'uses' => 'AdminDepoimentosController@editar']);
    Route::post('depoimentos/salvar',['as' => 'depoimentos.salvar', 'uses' => 'AdminDepoimentosController@salvar']);
    Route::post('depoimentos/atualizar/{id}',['as' => 'depoimentos.atualizar', 'uses' => 'AdminDepoimentosController@atualizar']);
    Route::get('depoimentos/delete/{id}',['as' => 'depoimentos.delete', 'uses' => 'AdminDepoimentosController@delete']);

    Route::get('users',['as' => 'users.index', 'uses' => 'AdminUsersController@index']);
    Route::get('users/novo',['as' => 'users.novo', 'uses' => 'AdminUsersController@novo']);
    Route::get('users/editar/{id}',['as' => 'users.editar', 'uses' => 'AdminUsersController@editar']);
    Route::post('users/salvar',['as' => 'users.salvar', 'uses' => 'AdminUsersController@salvar']);
    Route::post('users/atualizar/{id}',['as' => 'users.atualizar', 'uses' => 'AdminUsersController@atualizar']);
    Route::get('users/senha_editar/{id}',['as' => 'users.senha_editar', 'uses' => 'AdminUsersController@senha_editar']);
    Route::post('users/senha_atualizar/{id}',['as' => 'users.senha_atualizar', 'uses' => 'AdminUsersController@senha_atualizar']);
    Route::get('users/delete/{id}',['as' => 'users.delete', 'uses' => 'AdminUsersController@delete']);

    Route::get('cursos',['as' => 'cursos.index', 'uses' => 'AdminCursosController@index']);
    Route::get('cursos/novo',['as' => 'cursos.novo', 'uses' => 'AdminCursosController@novo']);
    Route::get('cursos/editar/{id}',['as' => 'cursos.editar', 'uses' => 'AdminCursosController@editar']);
    Route::post('cursos/salvar',['as' => 'cursos.salvar', 'uses' => 'AdminCursosController@salvar']);

resources/views/site/_contato_detalhes_include.blade.php
{!! $contato_texto['texto'] !!}

resources/views/site/_cursos_include.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="section-title text-center">
            <h4>Cursos</h4>
            <p>Cursos de LIBRAS - Nível I, II, III</p>
        </div>
    </div><!-- end col -->
</div><!-- end row -->

<div id="owl-featured" class="owl-custom">
    <div class="owl-featured">
        <div class="shop-item-list entry">
            <div class="">
                <img src="images/site/course_01.png" alt="">
                <div class="magnifier">
                </div>
            </div>
            <div class="shop-item-title clearfix">
                <h4><a href="#">Curso Nível I</a></h4>
                <div class="shopmeta">
                    <span class="pull-left">12 Alunos</span>
                    <div class="rating pull-right">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </div><!-- end rating -->
                </div><!-- end shop-meta -->
            </div><!-- end shop-item-title -->
            <div class="visible-buttons">
                <a title="Adicionar ao carrinho" href="#"><span class="fa fa-cart-arrow-down"></span></a>
                <a title="Leia mais" href="#"><span class="fa fa-search"></span></a>
            </div><!-- end buttons -->
        </div><!-- end relative -->
    </div><!-- end col -->

    <div class="owl-featured">
        <div class="shop-item-list entry">
            <div class="">
                <img src="images/site/course_02.png" alt="">
                <div class="magnifier">
                </div>
            </div>
            <div class="shop-item-title clearfix">
                <h4><a href="#">Curso Nível II</a></h4>
                <div class="shopmeta">
                    <span class="pull-left">21 Alunos</span>
                    <div class="rating pull-right">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                    </div><!-- end rating -->
                </div><!-- end shop-meta -->
            </div><!-- end shop-item-title -->
            <div class="visible-buttons">
                <a title="Adicionar ao carrinho" href="#"><span class="fa fa-cart-arrow-down"></span></a>
                <a title="Leia mais" href="#"><span class="fa fa-search"></span></a>
            </div><!-- end buttons -->
        </div><!-- end relative -->
    </div><!-- end col -->

    <div class="owl-featured">
        <div class="shop-item-list entry">
            <div class="">
                <img src="images/site/course_03.png" alt="">
                <div class="magnifier">
                </div>
            </div>
            <div class="shop-item-title clearfix">
                <h4><a href="#">Curso Nível III</a></h4>
                <div class="shopmeta">
                    <span class="pull-left">98 Alunos</span>
                    <div class="rating pull-right">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                    </div><!-- end rating -->
                </div><!-- end shop-meta -->
            </div><!-- end shop-item-title -->
            <div class="visible-buttons">
                <a title="Adicionar ao carrinho" href="#"><span class="fa fa-cart-arrow-down"></span></a>
                <a title="Leia mais" href="#"><span class="fa fa-search"></span></a>
            </div><!-- end buttons -->
        </div><!-- end relative -->
    </div><!-- end col -->

    <div class="owl-featured">
        <div class="shop-item-list entry">
            <div class="">
                <img src="images/site/course_04.png" alt="">
                <div class="magnifier">
                </div>
            </div>
            <div class="shop-item-title clearfix">
                <h4><a href="#">Pacote de Cursos</a></h4>
                <div class="shopmeta">
                    <span class="pull-left">98 Alunos</span>
                    <div class="rating pull-right">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                    </div><!-- end rating -->
                </div><!-- end shop-meta -->
            </div><!-- end shop-item-title -->
            <div class="visible-buttons">
                <a title="Adicionar ao carrinho" href="#"><span class="fa fa-cart-arrow-down"></span></a>
                <a title="Leia mais" href="#"><span class="fa fa-search"></span></a>
            </div><!-- end buttons -->
        </div><!-- end relative -->
    </div><!-- end col -->
</div><!-- end owl-featured -->

resources/views/site/contato.blade.php
@extends('layout')

@section('content')
    <section class="white section">
        <div class="container">
            <div class="row contact-wrapper">
                <div class="col-md-9 col-sm-9 col-xs-12 content-widget">
                    <div class="widget-title">
                        <h4>Formulário de Contato</h4>
                        <hr>
                    </div>
                    <div id="contato" class="contact_form row">
                        <div id="message"></div>
                        <form id="contato_form" action="{{route('site.contato_enviar')}}" name="contato_form" method="post">
                            {!! Form::token() !!}

                            @if(!empty(Session::get('enviado')))
                                <div class="alert alert-success" role="alert">
                                    {{Session::get('enviado')}}
                                </div>
                                <br style="clear: both">
                            @endif

                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                <label class="label-site">
                                    <input type="text" name="nome" id="nome" class="form-control required" placeholder="Nome *">
                                    <span class="error-message"></span>
                                </label>
                                <label class="label-site">
                                    <input type="text" name="email" id="email" class="form-control required email" placeholder="E-mail *">
                                    <span class="error-message"></span>
                                </label>
                                <label class="label-site">
                                    <input type="text" name="telefone" id="telefone" class="form-control" placeholder="Telefone">
                                    <span class="error-message"></span>
                                </label>

                            </div>
                            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                <textarea class="form-control" name="mensagem" id="mensagem" rows="6" placeholder=""></textarea>
                                <button type="submit" value="enviar" id="submit" class="btn btn-primary btn-block">Enviar</button>
                            </div>
                        </form>
                    </div><!-- end contact-form -->
                </div><!-- end col -->

                <div class="col-md-3 col-sm-3 col-xs-12 content-widget">
                    <div class="widget-title">
                        <h4>Fale Conosco</h4>
                        <hr>
                    </div>
                    <div class="contact-list contato-texto">
                        @include('site._contato_detalhes_include')
                    </div><!-- end contact-list -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </section><!-- end section -->
@endsection

@section('scripts')
    <script src="{{ URL::asset('js/jquery-validation/jquery.validate.min.js') }}"></script>
    <script src="{{ URL::asset('js/jquery-validation/additional-methods.min.js') }}"></script>
    <script src="{{ URL::asset('js/jquery-validation/localization/messages_pt_BR.min.js') }}"></script>
    <script>
        $(function(){
            $.validator.addClassRules({
                required: {
                    required: true
                },
                minlength: {
                    minlength: 3
                },
                currency: {
                    required: true
                },
                email:{
                    email: true
                }
            });
            $('#contato_form').validate({
                //debug: true,
                errorClass:'error-message',
                validClass:'success',
                errorElement:'label',
                highlight: function (element, errorClass, validClass) {
                    $(element).parents("div.form-div-4").addClass("error-message has-error");

                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).parents(".error-message").removeClass("error-message has-error");
                }
            });
        });
    </script>
@endsection

resources/views/site/cultura_surdos.blade.php
@extends('layout')

@section('content')

    <section class="white section">
        <div class="container">
            
            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        <div class="widget-title">
                            <h4>{{$texto[0]['nome']}}</h4>
                            <hr>
                        </div>
                        {!! $texto[0]['texto'] !!}
                    </div>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        <div class="widget-title">
                            <h4>{{$texto[1]['nome']}}</h4>
                            <hr>
                        </div>
                        {!! $texto[1]['texto'] !!}
                    </div>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        <div class="widget-title">
                            <h4>{{$texto[2]['nome']}}</h4>
                            <hr>
                        </div>
                        {!! $texto[2]['texto'] !!}
                    </div>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        <div class="widget-title">
                            <h4>{{$texto[3]['nome']}}</h4>
                            <hr>
                        </div>
                        {!! $texto[3]['texto'] !!}
                    </div>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        <div class="widget-title">
                            <h4>{{$texto[4]['nome']}}</h4>
                            <hr>
                        </div>
                        {!! $texto[4]['texto'] !!}
                    </div>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        <div class="widget-title">
                            <h4>{{$texto[5]['nome']}}</h4>
                            <hr>
                        </div>
                        {!! $texto[5]['texto'] !!}
                    </div>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        <div class="widget-title">
                            <h4>{{$texto[6]['nome']}}</h4>
                            <hr>
                        </div>
                        {!! $texto[6]['texto'] !!}
                    </div>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        <div class="widget-title">
                            <h4>{{$texto[7]['nome']}}</h4>
                            <hr>
                        </div>
                        {!! $texto[7]['texto'] !!}
                    </div>
                </div>
            </div>
            <hr>

         </div>   
    </section><!-- end section -->

@endsection

resources/views/site/curriculo.blade.php
@extends('layout')

@section('content')

    <section class="white section">
        <div class="container">
            
            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        <div class="widget-title">
                            <h4>{{$texto[0]['nome']}}</h4>
                            <hr>
                        </div>
                        {!! $texto[0]['texto'] !!}
                    </div>
                </div>
            </div>

         </div>   
    </section><!-- end section -->

@endsection

resources/views/site/fotos.blade.php
@extends('layout')

@section('content')
    <section class="white section">
        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        <div class="widget-title">
                            <h4>Galeria de Fotos</h4>
                            <hr>
                        </div>

                        @foreach($fotos as $v)
                            <div class="row">
                                <div class="col-lg-3">
                                    <div>
                                        <a href="{{route('site.fotos_visualizar',['id' => $v->id])}}" rel="fotos_{{$v->id}}" class="title" title="{{$v->nome}}">
                                            <img src="{{asset($v->arquivo)}}" alt="" class="img-responsive">
                                        </a>
                                    </div>
                                </div>
                                <div class="col-lg-9" style="padding-top: 0; margin-top: 0;">
                                    <h4 style="padding-top: 0; margin-top: 0;">{{$v->nome}}</h4>
                                    <div>{{$v->descricao}}</div>
                                </div>
                            </div>
                            <br><br>

                        @endforeach

                    </div>
                </div>
            </div>

        </div>
    </section><!-- end section -->

@endsection

resources/views/site/fotos_visualizar.blade.php
@extends('layout')

@section('content')
    <section class="white section">
        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        @foreach($fotos as $v)
                            <div class="widget-title">
                                <h4>{{$v->nome}}</h4>
                                <hr>
                                <div>{{$v->descricao}}</div>
                            </div>

                            <div class="row">
                                <?php $i = 0;?>
                                @foreach($v->fotos as $v2)
                                    <div class="col-lg-3">
                                    @if(strpos($v2->arquivo,'youtube') === false)
                                        <a href="{{$v2->arquivo}}" rel="fotos_{{$v->id}}" class="title" title="{{$v2->legenda}}">
                                            {!!Thumb::img($v2->arquivo, 260)!!}
                                        </a>
                                    @else
                                        <a href="{{Youtube::embed($v2->arquivo)}}" rel="fotos_{{$v2->id}}" class="title fancybox.iframe" title="{{$v2->legenda}}"></a>
                                    @endif
                                    </div>
                                    <?php $i++; ?>
                                    @if($i % 4 == 0 && $i > 0)
                                        <br style="clear: both"><br>
                                    @endif
                                @endforeach
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </section><!-- end section -->

@endsection
@section('scripts')
    @include('includes.fancybox')
@endsection

resources/views/site/noticias.blade.php
@extends('layout')

@section('content')
    <section class="white section">
        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <div class="content-widget">
                        <div class="widget-title">
                            <h4>Últimas Notícias</h4>
                            <hr>
                        </div>

                        @foreach($noticias as $v)
                            <div class="col-lg-4 col-md-4 col-sm-4">
                                <div class="thumb-pad5 maxheight">
                                    <div class="thumbnail">
                                        <figure style="height: 191px; overflow: hidden;">
                                            @if(!empty($v->arquivo))
                                                <a href="{{route('site.noticia',['slug'=>$v->slug])}}"><img src="{{URL::asset($v->arquivo)}}" alt=""></a>
                                            @else
                                                <a href="{{route('site.noticia',['slug'=>$v->slug])}}"><img src="{{URL::asset('images/img-vazio.png')}}" alt=""></a>
                                            @endif
                                        </figure>
                                        <div class="caption">
                                            <time datetime="{{substr($v->created_at,0,10)}}">{{Formata::date(substr($v->created_at,0,10),'.')}}</time>
                                            <br>
                                            <a href="{{route('site.noticia',['slug'=>$v->slug])}}" class="description">{{$v->titulo}}</a>
                                            <p>{{Texto::resumo($v->texto)}}...</p>
                                            <a href="{{route('site.noticia',['slug'=>$v->slug])}}" class="btn-default btn1">mais...</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach

                        <div class="clearfix"></div>
                        <div class="col-lg-12 col-md-12 col-sm-12 centre-box">
                            <h2>Mais Artigos</h2>
                            @foreach($noticias2 as $v)
                                <div class="row">
                                    <div class="col-lg-3">
                                        <figure style="width:100%; overflow: hidden;">
                                            @if(!empty($v->arquivo))
                                                <a href="{{route('site.noticia',['slug'=>$v->slug])}}"><img src="{{URL::asset($v->arquivo)}}" alt="" style="width: 100%;"></a>
                                            @else
                                                <a href="{{route('site.noticia',['slug'=>$v->slug])}}"><img src="{{URL::asset('images/img-vazio.png')}}" alt=""></a>
                                            @endif
                                        </figure>
                                    </div>
                                    <div class="col-lg-9">
                                        <time datetime="{{substr($v->created_at,0,10)}}"><a href="{{route('site.noticia',['slug'=>$v->slug])}}">{{Formata::date(substr($v->created_at,0,10),'.')}}</a></time>
                                        <br>
                                        <a href="{{route('site.noticia',['slug'=>$v->slug])}}" class="description">{{$v->titulo}}</a>
                                        <p>{{Texto::resumo($v->texto)}}...</p>
                                    </div>
                                </div>
                                <div style="width: 100%; margin-top: 15px; border-top: 1px solid #F2F2F2;"></div>
                            @endforeach
                            <div>{!! $noticias2->render() !!}</div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section><!-- end section -->

@endsection